apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-rest-api
  labels:
    name: minikube-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minikube-rest-api
  template:
    metadata:
      name: minikube-rest-api
      labels:
        name: minikube-rest-api
    spec:
      containers:
        - image: lets/minikube-rest-api:latest
          imagePullPolicy: IfNotPresent
          name: minikube-rest-api
          ports:
            - containerPort: 8590
          envFrom:
            - configMapRef:
                name: minikube-rest-api-configmap
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]