apiVersion: v1
kind: Service
metadata:
  name: minikube-rest-api-service
spec:
  type: NodePort
  selector:
    name: minikube-rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
      nodePort: 30007